import { Request, Response } from 'express';
import { getCustomRepository } from 'typeorm';
import { AppError } from '../errors/AppError';
import { SurveyUsersRepository } from '../repositories/SurveyUsersRepositories';

/**
 * Class responsible for responding to the requests
 * generated by an user clicking a vote link on
 * the survey email
 */
class AnswerController {
    /**
     * Receives the answers provided from the user
     * by clicking on the email links and updates
     * the "value" column on the surveys_users db
     * @param request Request
     * @param response Response
     */
    async execute(request: Request, response: Response) {
        const { value } = request.params;
        const { u } = request.query;

        const surveyUsersRepository = getCustomRepository(SurveyUsersRepository);

        // Find the correct user from the db using their id as the key
        const surveyUser = await surveyUsersRepository.findOne({
            id: String(u)
        });

        // Throw an AppError in case the user ins't found in the db
        if (!surveyUser) {
            throw new AppError({
                message: "Survey User dos not exist.",
                statusCode: 400
            })
        };

        // Update the value with the answer and save it to the db
        surveyUser.value = Number(value);
        await surveyUsersRepository.save(surveyUser);

        return response.json(surveyUser);
    }
}

export { AnswerController }